name: Zip Resource Pack

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create the ZIP file
      - name: Create Resource Pack ZIP
        run: |
          zip -r flintix-pack.zip assets pack.mcmeta pack.png

      # Upload the ZIP file as an artifact (optional, you can remove this if not needed)
      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v3
        with:
          name: flintix-pack
          path: flintix-pack.zip

      # Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Flintix Pack Release v1.0${{ github.run_number }}"
          draft: false
          prerelease: false

      # Upload the ZIP file to the release
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./flintix-pack.zip
          asset_name: flintix-pack.zip
          asset_content_type: application/zip
